# Generated by Django 4.2.4 on 2023-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="file_upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UID", models.CharField(max_length=200)),
                ("이름", models.CharField(max_length=100)),
                ("사용일", models.DateField()),
            ],
            options={
                "unique_together": {("UID", "사용일")},
            },
        ),
    ]
