# Generated by Django 4.2.4 on 2023-08-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0002_remove_visitor_이름"),
    ]

    operations = [
        migrations.AddField(
            model_name="file_upload",
            name="구분",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
