# Generated by Django 4.2.4 on 2023-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyNewVisitors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("new_visitors_count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyNewVisitors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("new_visitors_count", models.PositiveIntegerField()),
            ],
            options={
                "unique_together": {("year", "month")},
            },
        ),
    ]
