# Generated by Django 4.2.4 on 2023-08-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="이름",
        ),
    ]
