# Generated by Django 4.2.4 on 2023-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="uploaded_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
