# Generated by Django 4.2.4 on 2023-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0002_visitor_uploaded_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
